### ISSUE TITLE
tutorial data

### ISSUE THREAD

**Issue by gregmacfarlane** [synthicity/pandana#40]
I'm trying to follow the tutorial in [tutorial.rst](https://github.com/synthicity/pandana/blob/master/docs/tutorial.rst), I can't find the example data called in 

    store = pd.HDFStore("data/osm_bayarea.h5", "r")

anywhere in the repository. In fact, the only place I can find this file is at the [MTC website](http://analytics.mtc.ca.gov/foswiki/UrbanSimTwo/InputFiles), but it appears to be behind a login wall.

Are you able to distribute this dataset? If not, is there a different hdf5 dataset that I should try out?

**Comment by fscottfoti** [comment]
Totally fine to share as it just came from OpenStreetMap.  I'll put it on our Dropbox acct for now.

https://www.dropbox.com/s/cycq0v6afckb1w1/osm_bayarea.h5?dl=0

Let me know if you have any trouble!

**Comment by gregmacfarlane** [comment]
Great, thank you.

**Comment by fillipefeitosa** [comment]
@fscottfoti 
Is it possible to make this file available again?

thanks for your time!
